### PR TITLE
fix: implement std::error::Error for data-url

### LINKED ISSUE #697: std::error::Error is not implemented for Errors in data-url crate
The `data-url` crate does not implement `std::error::Error` (and thus no human readable formatting) for the following errors in that crate:

- `DecodeError`
- `DataUrlError`
- `MimeParsingError`

Is there any reason for this? If not I would be glad to submit a PR.

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit implements std::error::Error for errors in the `data-url`
crate.

Closes #697

### CODE REVIEW

File: data-url/src/forgiving_base64.rs [hunk 1]
```diff
@@ -17,6 +32,18 @@ pub enum DecodeError<E> {
     WriteError(E),
 }
 
+impl<E> std::fmt::Display for DecodeError<E> {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        match self {
+            Self::InvalidBase64(inner) => write!(f, "base64 not valid: {:?}", inner),
```
Comment (djc) [inline data-url/src/forgiving_base64.rs:38]: Since we still support Rust 1.36, you'll have to write out the full enum name here.

**Comment by sunsided** [comment]
Hey @lucacasonato! I was looking for the exact same feature here. Any updates? 🙂

File: data-url/src/forgiving_base64.rs (hunk 1 above)
Comment (arpankapoor) [reply data-url/src/forgiving_base64.rs:38]: Could this please be merged now that the MSRV is 1.51?

**Comment by filips123** [comment]
With Servo [resuming its development in 2023](https://servo.org/blog/2023/01/16/servo-2023/), could this PR maybe be merged?

@lucacasonato Also, could you still implement `std::error::Error` on `DecodeError` and other errors where it's not already implemented? Based on [this comment](https://github.com/servo/rust-url/issues/697#issuecomment-817246265), it could be added even without a breaking change. But even if it's still a breaking change, it's a fairly small one, so it probably shouldn't matter if there is `0.2.0` after a few years since the last release.

**Comment by lucacasonato** [comment]
@valenting PTAL - this PR is rebased now.

**Review by valenting — APPROVED** [review]
